### ISSUE TITLE
URIBeacon2Service Needs initial AdvertisedTxPowerLevels

### ISSUE THREAD

**Issue by schilit** [ARMmbed/BLE_API#17]
Hi @rgrover @roywant

The UriBeaconConfigService (or the main.c) requires a default array for [Advertised Tx Power Levels](https://github.com/google/uribeacon/blob/master/specification/ConfigService.md#36-advertised-tx-power-levels). Indexing by the current mode results in the dBm value transmitted in the ADV packet.

Since the value used for `nRF51822n::setTxPower` may not be the same as the Advertised value we also recommend an array for this purpose.

`nRF51822n::setTxPower` takes values of `-40, -20, -16, -12, -8, -4, 0, 4`

Suggest
```
// Values included in ADV packets for
// TX_POWER_MODE_LOWEST through TX_POWER_MODE_HIGH
// TODO: adjust these values using measurements for the packaged device
uint8_t[4] advertisedTxPowerLevels = {-40, -20, -12, 4};

// Values for nRF51822n::setTxPower for
// TX_POWER_MODE_LOWEST through TX_POWER_MODE_HIGH
uint8_t[4] firmwareTxPowerLevels = {-40, -20, -12, 4};
```

**Comment by rgrover** [comment]
This has been resolved. Refer to https://github.com/ARMmbed/BLE_API/blob/master/ble/services/URIBeaconConfigService.h#L47. Please re-open if required.
